const getTimes = [
    { label: "12 am", value: 0 },
    { label: "01 am", value: 1 },
    { label: "02 am", value: 2 },
    { label: "03 am", value: 3 },
    { label: "04 am", value: 4 },
    { label: "05 am", value: 5 },
    { label: "06 am", value: 6 },
    { label: "07 am", value: 7 },
    { label: "08 am", value: 8 },
    { label: "09 am", value: 9 },
    { label: "10 am", value: 10 },
    { label: "11 am", value: 11 },
    { label: "12 pm", value: 12 },
    { label: "01 pm", value: 13 },
    { label: "02 pm", value: 14 },
    { label: "03 pm", value: 15 },
    { label: "04 pm", value: 16 },
    { label: "05 pm", value: 17 },
    { label: "06 pm", value: 18 },
    { label: "07 pm", value: 19 },
    { label: "08 pm", value: 20 },
    { label: "09 pm", value: 21 },
    { label: "10 pm", value: 22 },
    { label: "11 pm", value: 23 },
];

export default getTimes;
