// ## region [notification table constant]

export const NOTIFICATION_AGENCY_EVENT__TYPE__USER_REGISTRATION = 1;
export const NOTIFICATION_AGENCY_EVENT__TYPE__USER_BUY_PACKAGE = 2;
export const NOTIFICATION_AGENCY_EVENT__TYPE__USER_BALANCE_RECHARGE = 3;
export const NOTIFICATION_AGENCY_EVENT__TYPE__USER_RECURRING_BILLING_FAILED = 4;
export const NOTIFICATION_AGENCY_EVENT__TYPE__AGENCY_PACKAGE_EXPIRE = 5;

export const NOTIFICATION_AGENCY_SEEN_FLAG__SEEN = 1;
export const NOTIFICATION_AGENCY_SEEN_FLAG__NOT_SEEN = 0;

// ## region [Agency Activity Logs table export constant]

export const AGENCY_ACTIVITY_LOG__ACTION_TYPE__CREATE = 1;
export const AGENCY_ACTIVITY_LOG__ACTION_TYPE__UPDATE = 2;
export const AGENCY_ACTIVITY_LOG__ACTION_TYPE__DELETE = 3;
export const AGENCY_ACTIVITY_LOG__ACTION_TYPE__COMPLETED = 4;
export const AGENCY_ACTIVITY_LOG__ACTION_TYPE__OTHERS = 5;
